chore(lint): Fix eslint hound config
upfrontIO/apply-guides pull request #26
Opened 2017-01-17 15:18 UTC by vhf

2017-01-17 15:55 UTC, masone commented
You will also need to update the rule that is copying the file https://github.com/upfrontIO/apply-guides/blob/master/index.js#L16

I assume that if we write the json file, we will need to remove the non-json file manually. This is a good example that this approach for distributing files across repos is flawed. Sorry about that. We plan to improve that workflow https://github.com/upfrontIO/livingdocs-planning/issues/290

2017-01-17 15:56 UTC, masone requested changes
please also update the reference to the file in the code

2017-01-18 15:36 UTC, vhf commented
Ready @masone

2017-01-18 17:29 UTC, masone approved these changes

2017-01-19 08:41 UTC, merged