chore(lint): Some more rules enforcing consistency
upfrontIO/apply-guides pull request #27
Opened 2017-01-18 12:36 UTC by vhf

Here are a few more rules I feel are missing and would improve consistency.

2017-01-18 12:47 UTC, marcbachmann commented on static/.eslintrc
> +    "computed-property-spacing": [2, "never"],
Does `standard/computed-property-even-spacing` only cover newlines or didn't we install it properly?
https://github.com/upfrontIO/apply-guides/pull/27/files#diff-2072934b5106b60a8a6ffc4737a34a21R194

We depend on `eslint-plugin-standard`, which isn't installed in the editor.

2017-01-18 12:52 UTC, marcbachmann commented on static/.eslintrc
> +    "object-curly-spacing": [2, "always"],
Please keep it at `never`
https://github.com/upfrontIO/livingdocs/blob/master/contribution-guidelines/style-guides/coffeescript.md#our-rules

2017-01-18 12:53 UTC, marcbachmann commented on static/.eslintrc
> +    "no-nested-ternary": 2,
👍

2017-01-18 13:13 UTC, marcbachmann requested changes

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +    "no-mixed-operators": [2, {
👍

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +      "groups": [
> Default is the groups for each kind of operators.

I guess you can remove that property. That's used by default.

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +      "allowSamePrecedence": false
This isn't very reasonable for me.
e.g. `var foo = a + b - c;` wouldn't be allowed

http://eslint.org/docs/rules/no-mixed-operators#allowsameprecedence

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +    "no-lonely-if": 2,
http://eslint.org/docs/rules/no-lonely-if#rule-details

I'm using the second invalid example quite often
```js
if (condition) {
    // ...
} else {
    if (anotherCondition) {
        // ...
    } else {
        // ...
    }
}
```

Do you think that's hard to read?

and that would be valid.
```js
if (condition) {
    // ...
} else {
    if (anotherCondition) {
        // ...
    }
    doSomething();
}
```

IMO This rule can cause confusion if somebody needs to modify some existing code.

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +    "eol-last": [2, "always"],
🎉 This wasn't enforceable in coffee-script.
But isn't `always` the default?

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +    "newline-per-chained-call": [2, { "ignoreChainWithDepth": 4 }],
I guess that's fine. Do you think 3 is too low?

2017-01-18 13:13 UTC, marcbachmann commented on static/.eslintrc
> +    "multiline-ternary": ["off", "never"],
Hmm. they are more readable than on one line.
IMO prevent nested ternaries is good enough.

2017-01-18 14:14 UTC, vhf commented on static/.eslintrc
> +    "computed-property-spacing": [2, "never"],
It depends whether we really want consistent style or not. `even` only enforces you put N spaces after `[` and before `]`. N can be 0, 1, ...

I'd rather have a strict rule saying `foo[bar]` so N = 0.

2017-01-18 14:16 UTC, marcbachmann commented on static/.eslintrc
> +    "computed-property-spacing": [2, "never"],
Yes, that's better 👍 
Can we remove the other config then?

2017-01-19 10:13 UTC, vhf commented
@masone this one is ready, we discussed each rule together with @marcbachmann and @peyerluk .

2017-01-19 10:13 UTC, vhf commented
Should I fix `index.js` by the way?

2017-01-19 10:15 UTC, marcbachmann commented
> Should I fix index.js by the way?

Yes, please. Thanks.

2017-01-19 10:15 UTC, livingdocs-automation commented
Thanks for pushing forward on this! I like!

2017-01-19 10:15 UTC, marcbachmann commented
Our bot is happy :grin:

2017-01-19 10:16 UTC, masone commented
Thanks for pushing forward on this! I like!

2017-01-19 10:17 UTC, marcbachmann commented
@masone you just made comment confusing by deleting the one of the bot -.-

2017-01-19 10:29 UTC, marcbachmann approved these changes

2017-01-19 10:31 UTC, merged